<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Register_model extends CI_Model
{

    public $table = 'register';
    public $id = 'idreg';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idreg', $q);
	$this->db->or_like('institution', $q);
	$this->db->or_like('nameofcp', $q);
	$this->db->or_like('position', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('mobile', $q);
	$this->db->or_like('s_title', $q);
	$this->db->or_like('s_fname', $q);
	$this->db->or_like('s_lname', $q);
	$this->db->or_like('s_gender', $q);
	$this->db->or_like('s_position', $q);
	$this->db->or_like('s_email', $q);
	$this->db->or_like('s_telp', $q);
	$this->db->or_like('s_mobile', $q);
	$this->db->or_like('s_foodrest', $q);
	$this->db->or_like('s_package', $q);
	$this->db->or_like('s_arrival', $q);
	$this->db->or_like('s_departure', $q);
	$this->db->or_like('c_title', $q);
	$this->db->or_like('c_fname', $q);
	$this->db->or_like('c_lname', $q);
	$this->db->or_like('c_gender', $q);
	$this->db->or_like('c_position', $q);
	$this->db->or_like('c_email', $q);
	$this->db->or_like('c_telp', $q);
	$this->db->or_like('c_mobile', $q);
	$this->db->or_like('c_foodrest', $q);
	$this->db->or_like('c_package', $q);
	$this->db->or_like('c_arrival', $q);
	$this->db->or_like('c_departure', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idreg', $q);
	$this->db->or_like('institution', $q);
	$this->db->or_like('nameofcp', $q);
	$this->db->or_like('position', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('mobile', $q);
	$this->db->or_like('s_title', $q);
	$this->db->or_like('s_fname', $q);
	$this->db->or_like('s_lname', $q);
	$this->db->or_like('s_gender', $q);
	$this->db->or_like('s_position', $q);
	$this->db->or_like('s_email', $q);
	$this->db->or_like('s_telp', $q);
	$this->db->or_like('s_mobile', $q);
	$this->db->or_like('s_foodrest', $q);
	$this->db->or_like('s_package', $q);
	$this->db->or_like('s_arrival', $q);
	$this->db->or_like('s_departure', $q);
	$this->db->or_like('c_title', $q);
	$this->db->or_like('c_fname', $q);
	$this->db->or_like('c_lname', $q);
	$this->db->or_like('c_gender', $q);
	$this->db->or_like('c_position', $q);
	$this->db->or_like('c_email', $q);
	$this->db->or_like('c_telp', $q);
	$this->db->or_like('c_mobile', $q);
	$this->db->or_like('c_foodrest', $q);
	$this->db->or_like('c_package', $q);
	$this->db->or_like('c_arrival', $q);
	$this->db->or_like('c_departure', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Register_model.php */
/* Location: ./application/models/Register_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-06 11:18:58 */
/* http://harviacode.com */